" Author: Isa Cichon
" When started as "evim", evim.vim will already have done these settings. {{{
if v:progname =~? "evim"
  finish
endif " }}}
" vim-plug {{{
call plug#begin('~/.vim/plugged')
Plug 'bronson/vim-visual-star-search'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'editorconfig/editorconfig-vim'
Plug 'junegunn/gv.vim'
Plug 'NLKNguyen/papercolor-theme'
Plug 'shumphrey/fugitive-gitlab.vim'
Plug 'tpope/vim-dispatch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-rhubarb'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
call plug#end()
" }}}
" Misc {{{
behave xterm
filetype plugin indent on

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" keep 50 lines of command line history
set history=50

" don't create a viminfo file
set viminfo=""

" make Y behave like C and D
nnoremap Y y$

" shows matching parentheses when inserting one
set showmatch

" only insert one space when using J
set nojoinspaces

" set the internal encoding and make a greater effort to determine whether a
" file is in utf-8 without byte order mark
set encoding=utf-8

" use tmux escape sequences and set window title
set t_ts=]2;
set t_fs=\\
set title

" visual line breaks at 'breakat' characters
set wrap linebreak

if executable('rg')
    set grepprg=rg\ --line-number
endif
" }}}
" Mouse {{{
if has('mouse') " use the mouse if compiled with support for mouse
  set mouse=a
  " scroll through time
  nnoremap <A-ScrollWheelUp> g-
  nnoremap <A-ScrollWheelDown> g+
endif
" }}}
" Colors {{{
" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if &t_Co > 2 || has("gui_running")
  if !exists("g:syntax_on")
    syntax enable
  endif
  set background=light
  colorscheme PaperColor
  if has("win32") || has("win16")
    set guifont=Courier_New:h10:cANSI:qDRAFT
  else
    set guifont=Fira\ Mono\ 12
  endif
endif
" }}}
" Tabs & Indents {{{
" always use 4 spaces
set softtabstop=4   " number of spaces in tab when editing
set shiftwidth=4    " number of spaces to use for each step of autoindents
set shiftround      " Round indent to multiple of 'shiftwidth'.
set expandtab       " insert spaces instead of \t
set nosmartindent
set autoindent      " always set autoindenting on
" }}}
" UI Layout {{{
set number          " displays line-numbering at the start of every line
set relativenumber  " displays relative line-numbering to make jumping around easier
set ruler           " show the cursor position all the time
set showcmd         " display incomplete commands
set nocursorline    " don't highlight current line
set wildmenu        " add a menu for command-line completion (like in :e foo<TAB>)
set lazyredraw      " don't redraw while executing macros, registers, or other commands that have not been typed
set guioptions+=c   " use console dialogs instead of popup dialogs for simple choices
set guioptions-=m   " menubar
set guioptions-=T   " toolbar
set guioptions-=r   " right-hand scrollbar
set guioptions-=l   " left-hand scrollbar
set guioptions-=R   " right-hand scrollbar when there is a vertically split window
set guioptions-=L   " left-hand scrollbar when there is a vertically split window
set guioptions-=b   " bottom scrollbar
set guicursor=n-v-c-ve-o-i-ci-r-cr-sm:block-Cursor/lCursor-blinkoff0
" }}}
" Searching {{{
set ignorecase smartcase    " ignore case when searching without capital letters
set incsearch               " search as characters are entered
set hlsearch                " highlight all visible matches
" make backspace remove search highlights
" first one is necessary for ideavim
nnoremap <bs> :nohlsearch<cr>
nnoremap <silent><bs> :nohlsearch<cr>
nnoremap <leader>/ /\<\><left><left>
" }}}
" Folds {{{
set foldenable          " don't use folds
set foldlevelstart=10   " open most folds by default
set foldnestmax=10      " never use more than 10 folds
set foldmethod=syntax   " fold based on indent level
" }}}
" Backups {{{
set backup      " keep a backup file
set writebackup " use a backup file when trying to write a file
" move file~ and .file.un~ from working directory
if has("win32") || has("win16")
  set backupdir=$TEMP//,c:/tmp//,c:/temp//,.
  set directory=$TEMP//,c:/tmp//,c:/temp//,.
  set viewdir=$HOME/vimfiles/view
else
  set backupdir='~/.vim-tmp//,~/.tmp//,~/tmp//,/var/tmp//,/tmp//,.'
  set directory='~/.vim-tmp//,~/.tmp//,~/tmp//,/var/tmp//,/tmp//,.'
endif
" }}}
" Buffers {{{
set hidden
" use arrows to resize window
nnoremap <silent><Left> :vertical resize -1<CR>
nnoremap <silent><Right> :vertical resize +1<CR>
nnoremap <silent><Up> :resize +1<CR>
nnoremap <silent><Down> :resize -1<CR>
set splitright " open a new window on the right of the currently active with :vs
set splitbelow " open a new window below the currently active with :vs
" }}}
" Leader {{{
let mapleader = "\\"
map <space> <leader>
nnoremap <leader>w :w<cr>
" }}}
" Clipboard {{{
" use + register by default
if has('xterm_clipboard')
    if has('unnamedplus')
        set clipboard=unnamedplus
    else
        set clipboard=unnamed
    endif
endif
" copy to tmux buffer
function YankToTmux()
    if (v:event["regname"] == "") || (v:event["regname"] == "+")
        let l:content = v:event["regcontents"]->join("\n")
        if (v:event["regtype"] ==# "V") || (v:event["regtype"] =~ "^")
            let l:content .= "\n"
        endif
        let l:content = shellescape(l:content)
        call system("tmux set-buffer -- " . l:content)
    endif
endfunction
if has('autocmd') && has_key(environ(), "TMUX")
    " autocmd TextYankPost * call YankToTmux()
endif
nnoremap <leader>p o<esc>p
nnoremap <leader>P O<esc>p
" }}}
" Vimrc {{{
nnoremap <leader>ve :next $MYVIMRC<cr>
nnoremap <leader>vs :split $MYVIMRC<cr>
nnoremap <leader>vv :vsplit $MYVIMRC<cr>
" }}}
" Spelling {{{
"set default spelling languages to english and german
set spelllang=de,en_us
" enable completion by dictionary when spelling is enabled
set complete=.,w,b,u,t,i,kspell
" }}}
" Movement {{{
noremap <silent> <expr> j (v:count == 0 ? 'gj' : 'j')
noremap <silent> <expr> k (v:count == 0 ? 'gk' : 'k')
" window movement
nnoremap <c-h> <c-w>h
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-l> <c-w>l
" }}}
" Abbreviations {{{
iabbrev hte the
iabbrev waht what
" }}}
" jedi-vim {{{
let g:jedi#completions_command = ""
" }}}
" ctrlp {{{
if executable('fd')
    let g:ctrlp_user_command = 'fd . %s --type f '
else
    let g:ctrlp_user_command = ['.git', 'cd %s && git ls-files . -co --exclude-standard', 'find %s -type f']
endif
" }}}

" vim:foldmethod=marker:foldlevel=0
