# install plug.kak plugin that manages plugins
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "robertmeta/plug.kak" noload

set-option global startup_info_version 20200901
add-highlighter global/ number-lines -relative -separator " " -hlcursor -min-digits 3

# delete with D aswell for convenience
map -docstring "delete" global normal D d

# scrolling
map -docstring "scroll down" global normal <c-e> vj
map -docstring "scroll up" global normal <c-y> vk

# copy to X11 clipboard
hook global RegisterModified '"' %{ nop %sh{
    [ -n "$TMUX" ] && tmux set-buffer -- "$kak_main_reg_dquote"
    [ -n "$DISPLAY" ] && printf %s "$kak_main_reg_dquote" | xclip -in -selection clipboard >&- 2>&-
}}
# paste from X11 clipboard
map -docstring "paste before" global user P "!xclip -out -selection clipboard<ret>"
map -docstring "paste after" global user p "<a-!>xclip -out -selection clipboard<ret>"

# case insensitive search
map -docstring "case insensitive search" global normal / /(?i)
map -docstring "case insensitive backwards search" global normal <a-/> <a-/>(?i)
